import { globals } from './contentful-globals-content'
import { page } from './contentful-page-content'
import { navigationSection } from './contentful-navigation-section-content'
import { navigationSegment } from './contentful-navigation-segment-content'
import { textSection } from './contentful-text-section-content'
import { topicSection } from './contentful-topic-section-content'
import { topic } from './contentful-topic-content'
import { navigationAction } from './contentful-navigation-action-content'
